version: "3.7"

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  mongo-data:
    driver: local

services:

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: prod.Dockerfile
    ports:
      - 8761:8761

  fta:
    build:
      context: ./fta
      dockerfile: prod.Dockerfile
    ports:
      - 80:80
    depends_on:
      - mongo_db
      - eureka-server

  email-service:
    build:
      context: ./email-service
      dockerfile: prod.Dockerfile
    depends_on:
      - eureka-server

  fraud-service:
    build:
      context: ./fraud-service
      dockerfile: prod.Dockerfile
    depends_on:
      - eureka-server

  transactions-generator-service:
    build:
      context: ./transactions-generator-service
      dockerfile: prod.Dockerfile
    depends_on:
      - eureka-server

  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
