version: "3.7"

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  mongo-data:
    driver: local

services:

  fta:
    image: "wesleymime/fta-mono"
    restart: always
    ports:
      - 80:8080
    entrypoint: ["java","-Dspring.profiles.active=dev","-DMAIL_USERNAME=changeEmail","-DMAIL_PASSWORD=changePassword","-jar","/app.jar"]
    depends_on:
      - mongo_db
      
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  