version: "3.7"

volumes:
  mongo-data:
    driver: local

services:

  fta:
    build: .
    restart: always
    ports:
      - 80:8080
    depends_on:
      - mongo_db
      
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  