spring:
  application:
    name: transactions-generator-service
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true