apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  mongodb-url: mongodb
  kafka-url: http://kafka:9092
  eureka-url: http://eureka-server:8761/eureka
  bootadmin-url: http://eureka-server:8761/admin

