apiVersion: apps/v1
kind: Deployment
metadata:
  name: fta
  labels:
    app: fta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fta
  template:
    metadata:
      labels:
        app: fta
    spec:
      containers:
        - name: fta
          image: wesleymime/fta
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8080
          env:
            - name: server.port
              value: "8080"
            - name: spring.data.mongodb.host
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: mongodb-url
            - name: spring.data.mongodb.username
              valueFrom:
                secretKeyRef:
                  name: prod-secrets
                  key: mongodb-user
            - name: spring.data.mongodb.password
              valueFrom:
                secretKeyRef:
                  name: prod-secrets
                  key: mongodb-password
            - name: kafka.bootstrapAddress
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: kafka-url
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: eureka-url
---
apiVersion: v1
kind: Service
metadata:
  name: fta-service
spec:
  selector:
    app: fta
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080