apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-generator
  labels:
    app: transactions-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transactions-generator
  template:
    metadata:
      labels:
        app: transactions-generator
    spec:
      containers:
        - name: transactions-generator
          image: wesleymime/generator
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 500Mi
          env:
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: eureka-url