global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'fta'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [fta:8080]
    basic_auth:
      username: 'admin@email.com.br'
      password: '123999'
