spring:
  application:
    name: fta
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  instance:
    preferIpAddress: true
feign:
  circuitbreaker:
    enabled: true
