spring:
  application:
    name: fta
  output:
    ansi:
      enabled: ALWAYS
  boot:
    admin:
      client:
        url: http://localhost:8761/admin
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  instance:
    preferIpAddress: true
feign:
  circuitBreaker:
    enabled: true
  client:
    config:
      default:
        loggerLevel: BASIC
logging:
  level:
    br.com.fta.transaction.application: DEBUG

kafka:
  bootstrapAddress: ${BROKER_URI:http://localhost:9092}