server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
      response-cache-auto-expiration-in-seconds: 30
spring:
  application:
    name: eureka-server
  output:
    ansi:
      enabled: ALWAYS
  boot:
    admin:
      context-path: /admin