apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: wesleymime/email
          env:
            - name: spring.profiles.active
              value: "dev"
            - name: kafka.bootstrapAddress
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: kafka-url
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: eureka-url
            - name: spring.boot.admin.client.url
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: bootadmin-url