apiVersion: apps/v1
kind: Deployment
metadata:
  name: fta
  labels:
    app: fta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fta
  template:
    metadata:
      labels:
        app: fta
    spec:
      containers:
        - name: fta
          image: wesleymime/fta
          ports:
            - containerPort: 80
          env:
            - name: spring.data.mongodb.host
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: mongodb-url
            - name: spring.data.mongodb.username
              valueFrom:
                secretKeyRef:
                  name: dev-secrets
                  key: mongodb-user
            - name: spring.data.mongodb.password
              valueFrom:
                secretKeyRef:
                  name: dev-secrets
                  key: mongodb-password
            - name: kafka.bootstrapAddress
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: kafka-url
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: eureka-url
---
apiVersion: v1
kind: Service
metadata:
  name: fta-service
spec:
  type: LoadBalancer
  selector:
    app: fta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80