apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-generator
  labels:
    app: transactions-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions-generator
  template:
    metadata:
      labels:
        app: transactions-generator
    spec:
      containers:
        - name: transactions-generator
          image: wesleymime/generator
          env:
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: eureka-url