spring:
  application:
    name: email-service
  output:
    ansi:
      enabled: ALWAYS
  boot:
    admin:
      client:
        url: ${EUREKA_URI:http://localhost:8761}/admin
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  instance:
    preferIpAddress: true

kafka:
  bootstrapAddress: ${BROKER_URI:http://localhost:9092}